name: Test `json-items-to-files` action
on:
  push:
    branches:
      - main

jobs:

  test-flat-json:
    runs-on: [ "ubuntu-latest" ]
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Unwrap JSON
        id: unwrap_json
        uses: ./ # Uses an action in the root directory
        with:
          input: '["1.0.0","1.1.0","1.2.0","1.2.1","1.3.0"]'
      - name: Echo output
        run: |
          echo "${{ steps.unwrap_json.outputs.result }}"
          ls -la
          cat "1.json"

  test-nested-json:
    runs-on: [ "ubuntu-latest" ]
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Unwrap nested JSON
        id: unwrap_json_nested
        uses: ./ # Uses an action in the root directory
        with:
          input: '[{"name":"v0.3.26","tag_name":"v0.3.26","prerelease":false,"published_at":"2023-08-07T09:43:28Z"},{"name":"v0.3.22","tag_name":"v0.3.22","prerelease":false,"published_at":"2023-11-12T10:58:00Z"},{"name":"v0.3.23","tag_name":"v0.3.23","prerelease":false,"published_at":"2023-11-12T10:59:27Z"},{"name":"v0.3.25","tag_name":"v0.3.25","prerelease":false,"published_at":"2023-11-12T11:01:20Z"},{"name":"v0.3.31","tag_name":"v0.3.31","prerelease":false,"published_at":"2023-11-12T11:17:17Z"},{"name":"v0.3.34","tag_name":"v0.3.34","prerelease":false,"published_at":"2023-11-12T11:21:59Z"}]'
          type: "nested-json"
          key: "name"
          extension: txt
      - name: Echo output
        run: |
          echo "${{ steps.unwrap_json_nested.outputs.result }}"
          ls -la
          cat "v0.3.26.txt"
